[features]
seeds = false
[programs.devnet]
solana_app = "77iNmGEeh3ks2XSkGCaHeYeePhNGn1Dei2CEMkAssFx9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/Anh.Le/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
